accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("professionals/", views.professionals, name='professionals'),
    path("<str:username>/", views.detail, name='detail'),
    path("edit/<int:pk>/", views.edit_profile_text, name='edit_profile_text'),
    path("edit/picture/", views.edit_profile_pic, name='edit_profile_pic'),
]

blog/urls.py
from django.urls import path 
from . import views 

app_name ='blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
]

conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('<int:user_pk>/', views.detail, name='detail'),
    path('new/<int:user_pk>/', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
]

ew/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .forms import LogInForm
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', LoginView.as_view(template_name='ew/login.html', authentication_form=LogInForm), name="login"),
    path('logout/', views.logout_view,  name='logout'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
]

forum/urls.py
from django.urls import path 
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
]

hmk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .views import index
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500

urlpatterns = [
    path('atarysworld/', admin.site.urls),
    path('', index, name='index'),
    path('embracewellness/', include('hmk.ew.urls')),
    path('embracewellness/forum/', include('hmk.forum.urls')),
    path('embracewellness/blog/', include('hmk.blog.urls')),
    path('embracewellness/profile/', include('hmk.accounts.urls')),
    path('embracewellness/conversation/', include('hmk.conversation.urls')),
    path('embracewellness/direct_messages/', include('hmk.contact.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hmk.ew.views.page_not_found'
handler403 = 'hmk.ew.views.permission_denied'
handler500 = 'hmk.ew.views.server_error'

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver 
from django.db.models.signals import post_save
from django.utils import timezone

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    avatar = models.ImageField(upload_to='avatar/', default='avatar/default.png')
    created_at = models.DateField(auto_now_add=True)
    modified_at = models.TimeField(auto_now=True)

    def __str__(self):
        return f'{self.user.username} Profile'
    
@receiver(post_save, sender=User)
def create_or_update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    else:
        try:
            instance.profile
        except Profile.DoesNotExist:
            Profile.objects.create(user=instance)
        else:
            instance.profile.save()

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm
from .models import Profile

INPUT_CLASSES =  'py-4 px-6 rounded-xl  w-[18rem] hover:border-mustard text-lg sm:w-[20rem] md:w-[80rem] bg-black placeholder:text-white cursor:text-white border border-white'

class UserForm(UserChangeForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'username', 'email']

    first_name = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your title...',
    'class': INPUT_CLASSES
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Your content...',
        'class': INPUT_CLASSES
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your title...',
    'class': INPUT_CLASSES
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your content...',
        'class': INPUT_CLASSES
    }))

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']


    avatar = forms.ImageField(widget=forms.FileInput(attrs={
        'placeholder': 'Your content...',
        'class': INPUT_CLASSES
    }))

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from .models import Profile
from hmk.forum.models import Forum
from hmk.blog.models import Blog
from django.contrib.auth.decorators import login_required
from .forms import ProfileForm, UserForm


def detail(request, username):
    user = get_object_or_404(User, username=username)
    profile = get_object_or_404(Profile, user=user)
    forums = Forum.objects.filter(created_by=user).all()[0:3]
    blogs = Blog.objects.filter(author=user).all()[0:3]
    user_is_staff = request.user.is_staff

    return render(request, 'accounts/detail.html', {
        'profile': profile,
        'forums': forums,
        'blogs': blogs,
        'user_is_staff': user_is_staff
    } )

@login_required
def edit_profile_pic(request):
    user_is_staff = request.user.is_staff
    profile = get_object_or_404(Profile, user=request.user)

    if request.method == "POST":
        profile_form = ProfileForm(request.POST, request.FILES, instance=profile)
        if profile_form.is_valid():
            profile_form.save(commit=True)
            return redirect(f'/embracewellness/profile/{profile.user.username}/')
    else:
        profile_form = ProfileForm(instance=profile)

    return render(request, 'accounts/edit_profile_pic.html', {
        'profile_form': profile_form,
        'user_is_staff': user_is_staff
    })

@login_required
def edit_profile_text(request, pk):
    user_is_staff = request.user.is_staff
    user = get_object_or_404(User, pk=pk)
    if request.method == "POST":
        user_form = UserForm(request.POST, instance=user)
        if user_form.is_valid():
            user_form.save(commit=True)
            return redirect(f'/embracewellness/profile/{user.username}/')
    else:
        user_form = UserForm(instance=user)

    return render(request, 'accounts/edit_profile_text.html', {
        'user_form': user_form,
        'user_is_staff': user_is_staff
    } )

def professionals(request):
    user_is_staff = request.user.is_staff
    professionals_count = User.objects.filter(is_staff=True).all().exclude(username='admin').count()

    professionals_list = []
    professionals = User.objects.filter(is_staff=True).all().exclude(username='admin')

    for professional in professionals:
        professionals_list.append(get_object_or_404(Profile, user=professional))

    print(professionals_list)

    return render(request, 'accounts/professionals.html', {
        'user_is_staff': user_is_staff,
        'professionals_list': professionals_list,
        'professionals_count': professionals_count
    })

accounts/templates/accounts/detail.html
{% extends 'ew/base.html' %}

{% block title %}Profile{% endblock %}


{% block content %}
<section class="flex flex-col pt-[5rem] justify-end items-center w-full">
    <div class="xl:w-4/5 w-full h-auto flex sm:flex-row flex-col items-center">
        {% if request.user == profile.user %}<a href="{% url 'accounts:edit_profile_pic' %}" class="sm:w-1/5 w-4/5 hover:font-bold flex flex-col items-center h-auto rounded-full hover:cursor-pointer">{% else %}<div class="sm:w-1/5 w-4/5 flex flex-col items-center h-auto rounded-full">{% endif %}
            <img class="{% if request.user == profile.user %} hover:blur-sm  {% endif %}rounded-full " src="{{ profile.avatar.url }}" alt="Rounded avatar">
            {% if request.user == profile.user %}
                <span class="text-white text-xl">
                    <i class="fa-solid fa-pen"></i>
                    EDIT
                </span>
            {% endif %}
        {% if request.user == profile.user %}</a>{% else %}</div>{% endif %}

        <div  class="h-auto mx-10 w-4/5 flex flex-col space-y-2 sm:justify-content justify-center items-start">
            <div class="flex flex-row space-x-2 items-center sm:justify-start justify-center">
                <h3 class="text-white lg:text-[2rem] text-3xl font-bold w-full">{{ profile.user.first_name }} {{ profile.user.last_name }}</h3>
                {% if request.user == profile.user %}
                    <a href="{% url 'accounts:edit_profile_text' profile.user.id %}" class="py-2 px-3 rounded-full border border-white">
                        <span>
                            <i class="fa-solid fa-pen"></i>
                        </span>
                    </a>
                {% else %}
                    <a href="{% url 'conversation:new' profile.user.id %}" class="py-2 px-3 rounded-full border border-white">
                        <span>
                            <i class="fa-solid fa-message"></i>
                        </span>
                    </a>
                {% endif %}

            </div>

            <p class="text-mustard uppercase flex flex-row justify-center items-center space-x-10 text-sm  font-semibold">
                <span>
                    @{{ profile.user.username }}
                </span>
            </p>
            <h3 class="text-white pt-6 text-xl font-bold w-full">I do me regardless</h3>
            <p class="text-mustard  text-sm flex sm:flex-row flex-col font-semibold  w-[40rem] sm:space-x-4 justify-start sm:items-center items-start">
                <span>
                    <i class="fa-regular fa-calendar"></i>
                    joined since {{ profile.created_at }}
                </span>
                <span>
                    <i class="fa-solid fa-microphone"></i>
                    {{ profile.user.forums.count }} forums created
                </span>
                <span>
                    <i class="fa-solid fa-blog"></i>
                    {{ profile.user.forums.count }} Blogs created
                </span>

            </p>

        </div>

    </div>

    <div class="sm:w-4/5  w-4/5  pt-4 {% if user.is_authenticated %} h-auto {% else %} h-auto {% endif %} flex sm:flex-row flex-col">
        <div class="sm:w-1/2 w-full overflow-auto">
            <h2 class="sm:text-2xl text-xl font-bold z-[2] text-white">Latest Forums</h2>
            {% if forums %}
                <!--Forum item-->
                {% for forum in forums %}
                <a href="{% url 'forum:detail' forum.id %}">
                    <div class="text-mustard text-sm my-4 font-semibold flex flex-col justify-center items-start">
                        <p> {{ forum.title }}</p>
                        <p class="text-white">created_at @ {{ forum.created_at }}</p>
                    </div>
                </a>
                {% endfor %}
            {% else %}
                <div class="text-mustard text-sm my-4 font-semibold flex flex-col justify-center items-center">
                    <p>No Forums by {{ profile.user.first_name }}</p>
                </div>

            {% endif %}
        </div>

        <div class="bg-black sm:w-1/2  w-full text-black flex flex-col items-start">
            <h2 class="sm:text-2xl text-xl font-bold z-[2] text-white">Latest Blogs</h2>
            {% if blogs %}
                <!--Forum item-->
                {% for blog in blogs %}
                <a href="{% url 'blog:detail' blog.id %}">
                    <div class="text-mustard text-sm my-4 font-semibold flex flex-col justify-center items-start">
                        <p> {{ blog.title }}</p>
                        <p class="text-white">created at @ {{ blog.created_at }}</p>
                    </div>
                </a>

                {% endfor %}
            {% else %}
                <div class="text-mustard text-sm my-4 font-semibold flex flex-col justify-center items-center">
                    <p>No blogs by {{ profile.user.first_name }} </p>
                </div>

            {% endif %}

        </div>
    </div>



</section>


{% endblock %}

accounts/templates/accounts/edit_profile_pic.html
{% extends 'ew/base.html' %}

{% block title %}Edit Profile{% endblock %}


{% block content %}
<div class="pt-[2.5rem] ">
    <div class="flex flex-col justify-center items-center my-10  sm:mx-[15rem]">
        <h2 class="sm:text-5xl text-4xl font-bold z-[2]">Edit Profile</h2>
        <p class=" sm:text-[5rem]  text-[3rem] text-[#343a40]  z-[1] font-extrabold sm:-mt-[4rem]  -mt-[2.5rem]">Edit</p>
    </div>
<div>
<div class="flex flex-row justify-center ">
    <div class="cols-span-3 flex flex-col justify-center items-center  h-auto  bg-black text-white rounded-xl">

        <form method='post' action="{% url  'accounts:edit_profile_pic' %}" enctype="multipart/form-data" class="flex flex-col justify-center items-start">

            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2 text-white">Profile Picture:</label><br>
                {{ profile_form.avatar }}
            </div>


            {% if profile_form.errors or profile_form.non_field_errors %}
                <div class="self-center mb-3 p-6 bg-red-100 rounded-xl text-black">
                    {% for field in profile_form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>
            {% endif %}


            <button class="self-center text-lg font-semibold m-[1rem] px-6 py-3 bg-black text-black rounded-3xl  bg-mustard   hover:bg-white  hover:text-white capitalize">Edit</button>

        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/edit_profile_text.html
{% extends 'ew/base.html' %}

{% block title %}Edit Profile{% endblock %}


{% block content %}
<div class="pt-[2.5rem] ">
    <div class="flex flex-col justify-center items-center my-10  sm:mx-[15rem]">
        <h2 class="sm:text-5xl text-4xl font-bold z-[2]">Edit Profile</h2>
        <p class=" sm:text-[5rem]  text-[3rem] text-[#343a40]  z-[1] font-extrabold sm:-mt-[4rem]  -mt-[2.5rem]">Edit</p>
    </div>
<div>
<div class="flex flex-row justify-center ">
    <div class="cols-span-3 flex flex-col justify-center items-center  h-auto  bg-black text-white rounded-xl">

        <form action="." method="post" class="flex flex-col justify-center items-start">

            {% csrf_token %}


            <div class="mb-3">
                <label class="inline-block mb-2 font-semibold text-white">First Name:</label><br>
                {{ user_form.first_name }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2 text-white">Last Name:</label><br>
                {{ user_form.last_name }}
            </div>

            <div class="mb-3">
                <label class="inline-block mb-2 text-white">Username:</label><br>
                {{ user_form.username }}
            </div>


            <div class="mb-3">
                <label class="inline-block mb-2 text-white">Email:</label><br>
                {{ user_form.email }}
            </div>


            {% if user_form.errors or user_form.non_field_errors %}
                <div class="self-center mb-3 p-6 bg-red-100 rounded-xl text-black">
                    {% for field in user_form %}
                        {{ field.errors }}
                    {% endfor %}
                </div>
            {% endif %}


            <button class="self-center text-lg font-semibold m-[1rem] px-6 py-3 bg-black text-black rounded-3xl  bg-mustard   hover:bg-white  hover:text-white capitalize">Edit</button>

        </form>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/professionals.html
{% extends 'ew/base.html' %}

{% block title %}Professionals{% endblock %}


{% block content %}
<div class="pt-[4rem] w-4/5 mx-auto">
    <div class="flex flex-col justify-center items-center my-10 mx-auto w-full">
        <h2 class="sm:text-5xl text-4xl font-bold z-[3]">Who do you want to talk to?</h2>
        <p class=" sm:text-9xl  text-5xl text-[#343a40]  font-extrabold sm:-mt-[3.5rem] z-[1]  -mt-[2rem]">Professionals</p>
        <p class="text-lg sm:-mt-[2rem] text-mustard   -mt-[1rem] text-center z-[2]">{{ professionals_count }} professional(s) available</p>
    </div>

    <div class="space-y-6 w-full">
        {% for professional in professionals_list %}
            <a href="{% url 'accounts:detail' professional.user.username %}">
                <div class="flex items-center gap-4  mb-4 text-wrap">
                    <img src="{{ professional.avatar.url }}" class=" w-10 md:w-20 h-auto rounded-full"  alt="">
                    <div class="font-medium dark:text-white">
                        <div class="text-lg">{{ professional.user.first_name }}  {{ professional.user.last_name }}</div>
                        <div class="text-sm text-gray-400">Joined in {{ professional.created_at }}</div>
                    </div>
                </div>
            </a>
        {% endfor %}
   </div>
</div>
{% endblock %}