accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("professionals/", views.professionals, name='professionals'),
    path("<str:username>/", views.detail, name='detail'),
    path("edit/<int:pk>/", views.edit_profile_text, name='edit_profile_text'),
    path("edit/picture/", views.edit_profile_pic, name='edit_profile_pic'),
]

blog/urls.py
from django.urls import path 
from . import views 

app_name ='blog'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
]

contact/urls.py
from django.urls import path 
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
]

ew/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .forms import LogInForm
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', LoginView.as_view(template_name='ew/login.html', authentication_form=LogInForm), name="login"),
    path('logout/', views.logout_view,  name='logout'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
]

forum/urls.py
from django.urls import path 
from . import views

app_name = 'forum'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('detail/<int:pk>/', views.detail, name='detail'),
]

hmk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .views import index
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500

urlpatterns = [
    path('atarysworld/', admin.site.urls),
    path('', index, name='index'),
    path('embracewellness/', include('hmk.ew.urls')),
    path('embracewellness/forum/', include('hmk.forum.urls')),
    path('embracewellness/blog/', include('hmk.blog.urls')),
    path('embracewellness/profile/', include('hmk.accounts.urls')),
    path('embracewellness/conversation/', include('hmk.conversation.urls')),
    path('embracewellness/direct_messages/', include('hmk.contact.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hmk.ew.views.page_not_found'
handler403 = 'hmk.ew.views.permission_denied'
handler500 = 'hmk.ew.views.server_error'

ew/models.py
from django.db import models

# Create your models here.

ew/forms.py
from django import forms
from django.contrib.auth.models import User
from hmk.accounts.models import Profile
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm

INPUT_CLASSES =  'py-4 px-6 rounded-xl  w-[18rem] hover:border-mustard text-lg sm:w-[20rem] md:w-[30rem] bg-black placeholder:text-white cursor:text-white border border-white'

class LogInForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your username',
    'class': INPUT_CLASSES
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': INPUT_CLASSES
    }))


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'username', 'email', 'password1', 'password2')

    first_name = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your first name',
    'class': INPUT_CLASSES
    }))


    last_name = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your last name',
    'class': INPUT_CLASSES
    }))

    username = forms.CharField(widget=forms.TextInput(attrs={
    'placeholder': 'Your username',
    'class': INPUT_CLASSES
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': 'Your email',
        'class': INPUT_CLASSES
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': INPUT_CLASSES
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat password',
        'class': INPUT_CLASSES
    }))


class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['avatar']

    avatar = forms.CharField(widget=forms.FileInput(attrs={
        'class': INPUT_CLASSES #'text-clip overflow-hidden pt-4 pb-[40rem] px-6  rounded-xl  w-[18rem] hover:border-mustard text-lg sm:w-[20rem] md:w-[80rem] bg-black placeholder:text-white cursor:text-white border border-white'
    }))

ew/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm
from django.contrib.auth import logout
from hmk.forum.models import Forum
from hmk.blog.models import Blog
from hmk.contact.forms import ContactForm
from django.contrib.auth.models import User


def privacy_policy(request):
    return render(request, "ew/privacy_policy.html")

def index(request):
    forums = Forum.objects.all()[0:3]
    blogs = Blog.objects.all()[0:3]
    user_is_staff = request.user.is_staff
    professionals = User.objects.filter(is_staff=True).all().exclude(username='admin').count()





    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save(commit=True)
            return redirect("core:index")

    else:
        form = ContactForm()

    # clean up forum
    for forum in forums:
        forum.content = forum.content[0:500] + "..."

    for blog in blogs:
        blog.content = blog.content[0:500] + "..."


    if not len(forums) == 3:
        forums = None
    if not len(blogs) == 3:
        blogs = None

    return render(request, "ew/index.html", {
        "forums": forums,
        "blogs": blogs,
        "form": form,
        "user_is_staff": user_is_staff,
        "professionals": professionals
    })

def signup(request):
    user_is_staff = request.user.is_staff
    if request.method == "POST":
        signup_form = SignUpForm(request.POST)

        if signup_form.is_valid():
            signup_form = signup_form.save(commit=True)
            return redirect('/embracewellness/login/')

    else:
        signup_form = SignUpForm()


    return render(request, 'ew/signup.html', {
        'signup_form': signup_form,
        'user_is_staff': user_is_staff
    })

def logout_view(request):
    logout(request)
    return redirect('/embracewellness/')

def permission_denied(request, exception):
    return render(request, 'ew/403.html', status=403)

def page_not_found(request, exception):
    return render(request, 'ew/404.html', status=404)

def server_error(request):
    return render(request, 'ew/500.html', status=500)

ew/templates/ew/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock %} | Embrace Wellness</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'images/favicon.png' %}" >
    <script src="https://cdn.tailwindcss.com"></script>
    <script>
        tailwind.config = {
          theme: {
            extend: {
              colors: {
                'mustard': '#ffc107',
              }
            }
          }
        }
    </script>
</head>
<body class="bg-black font-sans text-white">
    <nav class="fixed w-full z-[4] xl:flex xl:justify-center xl:space-x-72 p-5 bg-black  text-white shadow">
      <div class="flex items-center justify-between cursor-pointer uppercase text-2xl ">
        <span class="font-extrabold hover:text-mustard">
          <a href="{% url 'core:index' %}">embracewellness</a>
        </span>
        <span class="xl:hidden block hover:text-mustard text-3xl">
          <i name="menu" onclick="Menu(this)" class="fa-solid fa-bars"></i>
        </span>
      </div>
      <ul class="xl:flex xl:static z-[1] xl:z-auto absolute w-full xl:w-auto left-0 xl:pl-0 pl-1 xl:py-0 py-1 xl:opacity-100 opacity-0 transition-all top-[-400px] ease-in duration-500  bg-black text-white">


        {% if user_is_staff %}
          <li class="mx-4 xl:my-0 my-4"><a href="{% url 'contact:index' %}" class="text-lg no-underline hover:underline-offset-8 hover:underline transition-all ease-in duration-500  hover:text-mustard capitalize">direct messages</a></li>
        {% else %}
        <li class="mx-4 xl:my-0 my-4"><a href="{% url 'core:index' %}#About" class="text-lg no-underline hover:underline-offset-8 hover:underline transition-all ease-in duration-500  hover:text-mustard capitalize">about</a></li>
        <li class="mx-4 xl:my-0 my-4"><a href="{% url 'core:index' %}#Contact" class="text-lg no-underline hover:underline-offset-8 hover:underline transition-all ease-in duration-500  hover:text-mustard capitalize">contact</a></li>
        {% endif %}

        <li class="mx-4 xl:my-0 my-4"><a href="{% url 'blog:index' %}" class="text-lg no-underline hover:underline-offset-8 hover:underline transition-all ease-in duration-500  hover:text-mustard capitalize">blog</a></li>
        <li class="mx-4 xl:my-0 my-4"><a href="{% url 'forum:index' %}" class="text-lg no-underline hover:underline-offset-8 hover:underline transition-all ease-in duration-500  hover:text-mustard capitalize">forum</a></li>
        {% if user.is_authenticated %}
        <li class="mx-4 xl:my-0 my-4"><a href="{% url 'conversation:inbox' %}" class="text-lg no-underline hover:underline-offset-8 hover:underline transition-all ease-in duration-500  hover:text-mustard capitalize">inbox</a></li>
        <li class="mx-4 xl:my-0 my-4"><a href="{% url 'accounts:detail' user.username %}" class="text-lg no-underline hover:underline-offset-8 hover:underline transition-all ease-in duration-500  hover:text-mustard capitalize">profile</a></li>

        <li class="mx-4 xl:my-0 my-4"><a href="{% url 'core:logout' %}" class="text-lg font-semibold xl:px-6 xl:py-3 transition-all ease-in duration-500 hover:underline-offset-8 hover:underline hover:text-mustard hover:underline xl:hover:no-underline xl:bg-black xl:text-white xl:rounded-3xl xl:border xl:border-white   xl:hover:bg-mustard  xl:hover:text-white capitalize">log out</a></li>
        <li class="mx-4 xl:my-0 my-4">
          <button id="dropdownDefaultButton" onclick="Dropdown(this)"  data-dropdown-toggle="dropdown" type="button">
            <span class="text-lg font-semibold xl:px-6 xl:py-3  transition-all ease-in duration-500 hover:underline-offset-8 hover:underline hover:text-mustard  hover:underline xl:hover:bg-mustard xl:hover:no-underline text-white    xl:bg-mustard xl:text-black xl:rounded-3xl  xl:hover:text-white capitalize">
              Create
              <svg class="w-2.5 h-2.5 inline " aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 10 6">
              <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="m1 1 4 4 4-4"/>
              </svg>
            </span>
          </button>

          <!-- Dropdown menu -->
          <div id="dropdown" class="z-[-1] absolute top-[300px] hidden xl:top-[50px] bg-[#343a40] text-white divide-y divide-gray-100 rounded-lg shadow w-44">
            <ul class="py-2 text-sm text-gray-700 dark:text-gray-200" aria-labelledby="dropdownDefaultButton">
              <li>
                <a href="{% url 'forum:new' %}" class="block px-4 py-2 hover:bg-mustard">New Forum post</a>
              </li>
              <li>
                <a href="{% url 'blog:new' %}" class="block px-4 py-2 hover:bg-mustard">New Blog post</a>
              </li>
            </ul>
          </div>
        </li>
        {% else %}
          <li class="mx-4 xl:my-0 my-4"><a href="{% url 'core:signup' %}" class="text-lg font-semibold xl:px-6 xl:py-3 transition-all ease-in duration-500 hover:underline-offset-8 hover:underline hover:text-mustard xl:hover:bg-mustard hover:underline xl:hover:no-underline xl:bg-black text-white xl:rounded-3xl xl:border xl:border-white   xl:hover:bg-mustard  xl:hover:text-white capitalize">sign up</a></li>
          <li class="mx-4 xl:my-0 my-4"><a href="{% url 'core:login' %}" class="text-lg font-semibold xl:px-6 xl:py-3  transition-all ease-in duration-500 hover:underline-offset-8 hover:underline hover:text-mustard xl:hover:bg-mustard  hover:underline xl:hover:no-underline text-white    xl:bg-mustard xl:text-black xl:rounded-3xl  xl:hover:text-white xl:hover:bg-gray-200 capitalize">log in</a></li>
        {% endif %}
      </ul>
    </nav>
    {% block content %}
    {% endblock %}
    <footer class="xl:w-4/5  w-full my-2 mx-auto flex flex-col items-start xl:flex-row  xl:justify-center ">

      <div class="py-10 px-6 text-left flex flex-col justify-center items-center xl:items-start space-y-10 mx-auto xl:my-0 my-2 w-full xl:w-1/4" >
          <h3 class="text-2xl  text-[#f8f9fa] font-bold">About</h3>
          <p class="text-gray-300 text-lg">We provide interactive resources, supportive community, counseling services, educational workshops, emergency resources, awareness campaigns, personal journals, and volunteer opportunities to aid students in promoting mental health and addressing gender-based violence.</p>
          <div class="text-2xl flex flex-row space-x-2">
            <span>
              <i class="fa-brands cursor-pointer hover:bg-mustard fa-twitter py-3 px-3 rounded-full text-gray-300 bg-[#343a40]"></i>
            </span>
            <span>
              <i class="fa-brands  cursor-pointer hover:bg-mustard  fa-facebook-f py-3 px-4 rounded-full text-gray-300  bg-[#343a40]"></i>
            </span>
            <span>
              <i class="fa-brands  cursor-pointer  hover:bg-mustard fa-instagram py-3 px-3 rounded-full text-gray-300  bg-[#343a40]"></i>
            </span>
          </div>
      </div>
      <div class="py-10 text-left flex flex-col justify-content xl:items-start items-center space-y-10 xl:w-1/4 w-full xl:my-0 my-2 mx-auto" >
          <h3 class="text-2xl font-bold text-[#f8f9fa]">Links</h3>
          <ul class=" flex flex-col space-y-3 text-lg">
            <span class="text-gray-300">
              <i class=" text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Home
            </span>
            <span class="text-gray-300">
              <i class="text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              About
            </span>
            <span class="text-gray-300">
              <i class=" text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Services
            </span>
            <span class="text-gray-300">
              <i class=" text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Forum
            </span>
            <span class="text-gray-300">
              <i class="text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Contact
            </span>
          </ul>
      </div>
      <div class="py-10 text-left flex flex-col justify-content xl:items-start items-center space-y-10 xl:w-1/4 w-full xl:my-0 my-2 mx-auto" >
          <h3 class="text-2xl font-bold text-[#f8f9fa]">Services</h3>
          <ul class=" flex flex-col space-y-3 text-lg">
            <span class="text-gray-300">
              <i class="text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Interactive Resources
            </span>
            <span class="text-gray-300">
              <i class="text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Supportive Community
            </span>
            <span class="text-gray-300">
              <i class=" text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Counseling Services
            </span>
            <span class="text-gray-300">
              <i class=" text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Awareness Campaigns
            </span>
            <span class="text-gray-300">
              <i class="text-gray-300 text-lg fa-solid fa-arrow-right"></i>
              Blog
            </span>
          </ul>
      </div>
      <div class="py-10 text-left flex flex-col justify-content xl:items-start items-center space-y-10 xl:w-1/4 w-full xl:my-0 my-2 mx-auto" >
        <h3 class="text-2xl font-bold text-[#f8f9fa]">Have a Question?</h3>
        <div>
          <div class="flex space-x-2 mb-3">
            <span>
              <i class="fa-solid fa-location-dot text-lg text-gray-300"></i>
            </span>
            <p>	KM 12, Lagos/Ibadan Expressway, MFM Prayer City, Ogun State, Nigeria.</p>
          </div>
          <div class="flex space-x-2 mb-3">
            <span>
              <i class="fa-solid fa-phone text-lg text-gray-300"></i>
            </span>
            <p>+2348156123857</p>
          </div>
          <div class="flex space-x-2">
            <span>
              <i class="fa-solid fa-envelope text-lg text-gray-300"></i>
            </span>
            <p>embracewellness@mtu.edu.ng</p>
          </div>
        </div>


    </div>

    </footer>
    <div class="text-[#6c757d] text-center text-lg m-6 text-wrap">
      <span>
        Copyright &copy; 2024. Built with hope by <a href="https://twitter.com/tariyekorogha" class="cursor-pointer text-mustard  no-underline hover:underline hover:underline-offset-2">Atary</a>
      </span>
    </div>
    <script>
      function Menu(e) {
        let list = document.querySelector('ul');

        e.name === 'menu' ? (e.name = "close",e.classList.remove('fa-bars'),e.classList.add('fa-xmark'), list.classList.add('top-[70px]'), list.classList.add('opacity-100')) : (e.name = "menu", list.classList.remove('top-[80px]'),e.classList.remove('fa-xmark'),e.classList.add('fa-bars'), list.classList.remove('opacity-100'))
        var dropdown = document.getElementById("dropdown");
        dropdown.classList.remove("block");
        dropdown.classList.add("hidden");
      }
      function Dropdown(e) {
        var dropdown = document.getElementById("dropdown");
        if (dropdown.classList.contains("hidden")) {
            // If dropdown is currently hidden, remove "hidden" and add "block"
            dropdown.classList.remove("hidden");
            dropdown.classList.add("block");
        } else {
            // If dropdown is currently shown, remove "block" and add "hidden"
            dropdown.classList.remove("block");
            dropdown.classList.add("hidden");
        }
      }
    </script>
    <script src="https://kit.fontawesome.com/4a0b7f4f49.js" crossorigin="anonymous"></script>
</body>

</html>

ew/templates/ew/index.html
{% extends 'ew/base.html' %}
{% load static %}

{% block title %} Welcome {% endblock %}

{% block content %}
   <!-- First Landing -->
    <div class="text-white flex flex-col  transition-all ease-in duration-500 lg:flex-row mx-auto justify-center lg:text-left  mx-auto items-center -space-y-[10rem]">
        <div style="text-shadow: 2px 2px #000;" class="flex flex-col lg:text-left items-start space-y-10 lg:-mb-0 lg:py-0 sm:py-[10rem] py-[10rem] -mb-[30rem] sm:-mb-[40rem] lg:-mb-0-mr-[10rem]  lg:-mr-[15rem] lg:-mr-[10rem]">
            <p class="uppercase text-mustard font-semibold text-sm tracking-widest">hello!</p>
            <h1 class="sm:text-6xl  text-4xl font-extrabold">
                Welcome to <br>
                <span class="text-mustard">EmbraceWellness</span>
            </h1>
            <p class="sm:text-3xl text-2xl">It's okay.</p>
            <div>
                <a href="{% url 'accounts:professionals' %}">
                    <button class="uppercase font-semibold text-sm px-6 py-4 bg-mustard text-black rounded-3xl">
                        talk to us
                    </button>
                </a>
                <a href="{% url 'forum:new' %}">
                    <button class="uppercase font-semibold text-sm px-6 py-4 bg-black text-white rounded-3xl border border-white">
                        vent
                    </button>
                </a>

            </div>
        </div>
        <div class="z-[-1]">
            <img src="{% static 'images/bg_1.png' %}" class=" h-[38rem] sm:h-[45rem] lg:h-[50rem] md:h-[60rem] xl:h-[65rem] w-auto" alt="a warm embrace">
        </div>
    </div>

    <!-- About -->
    <div id="About" class="m-10">
        <div class="flex flex-row justify-center items-center">
            <div class="lg:block hidden">
                <img src="{% static 'images/bg_2.png' %}" class="h-auto w-[120rem]" alt="">
            </div>
            <div class="flex flex-col items-center lg:items-start">
                <h2 class="sm:text-5xl text-4xl font-bold z-[2]">About Us</h2>
                <p class=" sm:text-9xl  text-7xl text-[#343a40] z-[1]  font-extrabold -mt-[2rem] -ml-[2rem]">About</p>
                <p class="text-lg -mt-[2rem] mb-6 z-[3]">We provide interactive resources, supportive community, counseling services, educational workshops, emergency resources, awareness campaigns, personal journals, and volunteer opportunities to aid students in promoting mental health and addressing gender-based violence.</p>
                <p class="text-2xl">
                    <span class="text-mustard font-semibold">
                        {{ professionals }}
                    </span> Professional Counsellor(s) Available
                </p>
                <a href="{% url 'accounts:professionals' %}">
                    <button class="uppercase font-semibold text-sm px-6 py-4 bg-mustard text-black rounded-3xl">
                        talk to us
                    </button>
                </a>
            </div>
    </div>

    <!-- Forum First landing  -->
    <div class="flex flex-col justify-center w-4/5 items-center my-10 mx-auto ">
        <h2 class="sm:text-5xl text-4xl font-bold">Forum</h2>
        <p class=" sm:text-9xl  text-7xl text-[#343a40]  font-extrabold sm:-mt-[3.5rem]  -mt-[2rem]">Forum</p>
        <p class="text-lg sm:-mt-[2rem]   -mt-[1rem] text-center">Students, staff, and non-students are able to connect, share experiences, and seek advice through our online discussion forum and fostering a sense of unity and support. (Acts 2:42-47)</p>
    </div>

    <!-- Forum second landing  -->
    <div class="lg:flex lg:justify-center lg:items-center ">
        <div class="xl:grid-cols-3 lg:mx-auto lg:my-[2rem] lg:grid-cols-2 lg:grid  flex flex-col justify-center items-center  lg:gap-1">
            {% for forum in forums %}
            <!-- FORUM ELEMENT -->
            <div class="bg-[#343a40] p-4 lg:p-10 w-[21rem] sm:w-[22rem] md:w-[25rem] lg:w-[25rem] m-10 rounded-sm ">
                <a href="{% url 'forum:detail' forum.id %}" class="h-auto flex flex-col space-y-2 justify-content items-start">
                    <p class="text-mustard lg:text-3xl text-2xl font-extrabold">{{ forum.created_at }}</p>
                    <h3 class="text-white lg:text-3xl text-2xl">{{ forum.title }}</h3>
                    <a href="{% url 'accounts:detail' forum.created_by.id %}"><p class="uppercase text-lg text-white">{{ forum.created_by }}</p></a>
                    <p class="text-white text-lg"  >{{ forum.content }}</p>
                </a>
            </div>
            {% endfor %}
        </div>
    </div>

    <!-- VENT BUTTON -->
    <div class="flex justify-center items-center">
        <a href="{% url 'forum:new' %}">
            <button class="uppercase font-semibold -ml-2 text-sm px-12 py-5 bg-mustard text-black rounded-full ">
                vent
            </button>
        </a>
    </div>

    <!-- Blog First landing  -->
    <div class="flex flex-col justify-center items-center my-10 mx-auto w-4/5">
        <h2 class="sm:text-5xl text-4xl font-bold z-[3]">Our Blog</h2>
        <p class=" sm:text-9xl  text-7xl text-[#343a40]  font-extrabold sm:-mt-[3.5rem] z-[1]  -mt-[2rem]">Blog</p>
        <p class="text-lg sm:-mt-[2rem]   -mt-[1rem] text-center z-[2]">Students, staff, and non-students are able to connect, share experiences, and seek advice through our online blog  and fostering a sense of unity and support. (Acts 2:42-47)</p>
    </div>


    <div class="lg:flex lg:justify-center lg:items-center ">
        <div class="xl:grid-cols-3 lg:mx-auto lg:my-[2rem] lg:grid-cols-2 lg:grid  flex flex-col justify-center items-center  lg:gap-1">

            <!--Blog item-->
            {% for blog in blogs %}
                <div class="w-[20rem] sm:w-[20rem] md:w-[25rem] lg:w-[25rem] m-10 rounded-sm ">
                    <a href="{% url 'blog:detail' blog.id %}" class="h-auto flex flex-col space-y-2 justify-content items-start">
                        <img src="{{ blog.image.url }}" class="w-full h-auto">
                        <p class="text-mustard uppercase flex flex-row justify-center items-center space-x-10 text-sm ">
                            <span>
                                {{ blog.created_at }}
                            </span>
                            <a href="{% url 'accounts:detail' blog.author.id %}">
                                <span>
                                {{ blog.author }}
                                </span>
                            </a>
                            <span>
                                <i class="fa-solid  fa-message"></i>
                                {{ blog.author.blogs.count }}

                            </span>
                        </p>
                        <h3 class="text-white lg:text-2xl text-xl w-full">{{ blog.title }}</h3>
                        <p class="text-white text-[1rem]"  >{{ blog.content }}</p>
                    </a>
                </div>
            {% endfor %}

        </div>
    </div>

    <!-- CONTACT FIRST LANDING -->
    <div id="Contact" class="flex flex-col justify-center items-center mx-auto my-10 w-4/5">
        <h2 class="sm:text-5xl text-4xl font-bold z-[3]">Contact us</h2>
        <p class=" sm:text-9xl  text-7xl text-[#343a40]  font-extrabold sm:-mt-[3.5rem] z-[1]  -mt-[2rem]">Contact</p>
        <p class="text-lg sm:-mt-[2rem]   -mt-[1rem] text-center z-[2]">You can contact us via any of the following details below or directly with the form on the website</p>
    </div>

    <!-- contant second landing -->
    <div class="my-10  w-full mx-auto my-2">
        <div class="flex justify-center items-center">
            <div class="xl:block hidden">
                <img src="{% static 'images/bg_2.png' %}" class="h-auto w-[120rem]" alt="">
            </div>
            <form action="." method="post" class="flex flex-col justify-center items-center bg-white xl:w-4/5 w-full py-10 mx-auto my-2  space-y-2">

                {% csrf_token %}

                <div class="mb-3 w-full flex justify-center">
                    {% csrf_token %}
                    {{ form.name }}
                </div>
                <div class="mb-3 w-full flex justify-center">
                    {% csrf_token %}
                    {{ form.email }}
                </div>
                <div class="mb-3 w-full flex justify-center">
                    {% csrf_token %}
                    {{ form.subject }}
                </div>
                <div class="mb-3 w-full flex justify-center">
                    {% csrf_token %}
                    {{ form.message }}
                </div>

                {% if form.errors or form.non_field_errors %}
                    <div class="self-center mb-3 p-6 bg-red-100 rounded-xl text-black">
                        {% for field in form %}
                            {{ field.errors }}
                        {% endfor %}
                    </div>
                {% endif %}

                {% if form.form_is_valid %}
                    <div class="self-center mb-3 p-6 bg-green-100 rounded-xl text-white">
                        <p>Message Received</p>
                    </div>
                {% endif %}

                {% csrf_token %}
                <button class="uppercase font-semibold flex justify-center   text-sm px-12 py-5 bg-mustard text-black rounded-full ">
                    send message
                </button>
            </form>
    </div>






{% endblock %}