accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path("professionals/", views.professionals, name='professionals'),
    path("<str:username>/", views.detail, name='detail'),
    path("edit/<int:pk>/", views.edit_profile_text, name='edit_profile_text'),
    path("edit/picture/", views.edit_profile_pic, name='edit_profile_pic'),
]

conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('<int:user_pk>/', views.detail, name='detail'),
    path('new/<int:user_pk>/', views.new_conversation, name='new'),
    path('', views.inbox, name='inbox'),
]

ew/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .forms import LogInForm
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', LoginView.as_view(template_name='ew/login.html', authentication_form=LogInForm), name="login"),
    path('logout/', views.logout_view,  name='logout'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
]

hmk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .views import index
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500

urlpatterns = [
    path('atarysworld/', admin.site.urls),
    path('', index, name='index'),
    path('embracewellness/', include('hmk.ew.urls')),
    path('embracewellness/forum/', include('hmk.forum.urls')),
    path('embracewellness/blog/', include('hmk.blog.urls')),
    path('embracewellness/profile/', include('hmk.accounts.urls')),
    path('embracewellness/conversation/', include('hmk.conversation.urls')),
    path('embracewellness/direct_messages/', include('hmk.contact.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hmk.ew.views.page_not_found'
handler403 = 'hmk.ew.views.permission_denied'
handler500 = 'hmk.ew.views.server_error'

conversation/models.py
from django.db import models
from django.contrib.auth.models import User

class Conversation(models.Model):
    member1 = models.ForeignKey(User, related_name=f'member1_conversations', on_delete=models.DO_NOTHING)
    member2 = models.ForeignKey(User, related_name=f'member2_conversations', on_delete=models.DO_NOTHING)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)


    class Meta:
        ordering = ('-modified_at',)

    def __str__(self):
        return str(self.created_at)


class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE)

conversation/forms.py
from django import forms

from .models import ConversationMessage

class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'placeholder': "Type your message here",
                'class': 'bg-black text-white border border-white w-full h-[4rem] py-4 px-6 rounded-xl border'
            })
        }

conversation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from .models import Conversation
from .forms import ConversationMessageForm
from hmk.accounts.models import Profile


@login_required
def new_conversation(request, user_pk):
    user_is_staff = request.user.is_staff
    user = get_object_or_404(User, pk=user_pk)


    conversations = Conversation.objects.filter(member2=request.user, member1=user).first()
    if not conversations:
        conversations = Conversation.objects.filter(member1=request.user, member2=user).first()

    if conversations:
        return redirect(f'/embracewellness/conversation/{user_pk}')

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)
        if form.is_valid():
            conversation = Conversation.objects.create(member1=request.user, member2=user)
            conversation.save()

            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            return redirect(f'/embracewellness/conversation/{user_pk}')

    else:
        form= ConversationMessageForm()

    return render( request, 'conversation/new.html', {
        'form': form,
        'user_is_staff': user_is_staff
    })

@login_required
def inbox(request):
    user_is_staff = request.user.is_staff
    conversations1 = Conversation.objects.filter(member1 = request.user.id).all()
    conversations2 = Conversation.objects.filter(member2 = request.user.id).all()

    return render(request, 'conversation/inbox.html', {
        'conversations1': conversations1,
        'conversations2': conversations2,
        'user_is_staff': user_is_staff
    })

@login_required
def detail(request, user_pk):
    user_is_staff = request.user.is_staff
    user = get_object_or_404(User, pk=user_pk)
    profile = get_object_or_404(Profile, user=user)
    conversation = Conversation.objects.filter(member2=request.user, member1=user).first()
    if not conversation:
        conversation = Conversation.objects.filter(member1=request.user, member2=user).first()


    form = ConversationMessageForm()

    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)

        if form.is_valid():
            conversation_message = form.save(commit=False)
            conversation_message.conversation = conversation
            conversation_message.created_by = request.user
            conversation_message.save()

            conversation.save()

            return redirect(f'/embracewellness/conversation/{user_pk}')
    else:
        form = ConversationMessageForm( )

    return render(request, 'conversation/detail.html', {
        'conversation': conversation,
        'form': form,
        'profile':profile,
        'user_is_staff': user_is_staff
    })

conversation/templates/conversation/detail.html
{% extends 'ew/base.html' %}

{% block title %}Conversation{% endblock %}

{% block content %}
<div class="w-4/5 mx-auto  pt-[5rem]">

    <a href="{% url 'accounts:detail' profile.user.username%}" class="w-full">
        <div class="flex items-center gap-4 mb-4">
            <img class="w-20 h-auto rounded-full" src="{{ profile.avatar.url }}" alt="">
            <div class="font-medium dark:text-white">
                <div class="text-lg">{{ profile.user.first_name }} {{ profile.user.last_name }}</div>
                <div class="text-sm text-gray-400">@{{ profile.user.username }}</div>
            </div>
        </div>
    </a>


   <div class="space-y-6">
        {% for message in conversation.messages.all %}

            <div class="p-6 flex {% if message.created_by == request.user %} bg-black border border-white text-white {% else %} bg-mustard text-black {% endif %} rounded-xl">
                <div>
                    <p class="mb-4">
                        <strong>{{ message.created_by.username }}</strong> @ {{ message.created_at }}
                    </p>
                    <p>
                        {{ message.content }}
                    </p>
                </div>
            </div>
        {% endfor %}
   </div>

   <form action="." method="post" class="mt-6">
        {% csrf_token %}

        <div >
            <label class="inline-block mb-2 text-white">Message:</label><br>
            {{ form.content }}
        </div>

        <div class=" flex justify-end">
            <button class="self-end mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
        </div>

   </form>

</div>
{% endblock %}

conversation/templates/conversation/inbox.html
{% extends 'ew/base.html' %}
{% load static %}
{% block title %}Inbox{% endblock %}

{% block content %}
   <div class="pt-[4rem] w-4/5 mx-auto">

    <div id="Contact" class="flex flex-col justify-center items-center mx-auto my-10 w-4/5">
        <h2 class="sm:text-5xl text-4xl font-bold z-[3]">Inbox</h2>
        <p class="text-7xl text-[#343a40]  font-extrabold sm:-mt-[3.5rem] z-[1]  -mt-[2rem]">Inbox</p>
    </div>

   <div class="space-y-6 w-full">
        {% for conversation in conversations1 %}
          {% for message in conversation.messages.all %}
            {% if message.created_by != request.user %}
            <a href="{% url 'conversation:detail' conversation.member2.id %}">
                <div class="flex items-center gap-4 mb-4">
                    <img src="{% static 'images\message.jpg' %}" class="w-20 h-auto rounded-full"  alt="">
                    <div class="font-medium dark:text-white">
                        <div class="text-lg">{{ conversation.member2.first_name }} {{ conversation.member2.last_name }}</div>
                        <div class="text-sm text-gray-400">New message sent @ {{ conversation.modified_at }}</div>
                    </div>
                </div>
            </a>
            {% endif %}
          {% endfor %}
        {% endfor %}

        {% for conversation in conversations2 %}
          {% for message in conversation.messages.all %}
            {% if message.created_by != request.user %}
            <a href="{% url 'conversation:detail' conversation.member1.id %}">
                <div class="flex items-center gap-4 mb-4">
                    <img src="{% static 'images\message.jpg' %}"  class="w-20 h-auto rounded-full bg-grey-400"  alt="">
                    <div class="font-medium dark:text-white">
                        <div class="text-lg">{{ conversation.member1.first_name }} {{ conversation.member1.last_name }}</div>
                        <div class="text-sm text-gray-400">New message sent @ {{ conversation.modified_at }}</div>
                    </div>
                </div>
            </a>
            {% endif %}
          {% endfor %}
        {% endfor %}
   </div>

   </div>
{% endblock %}

conversation/templates/conversation/new.html
{% extends 'ew/base.html' %}

{% block title %}New conversation{% endblock %}

{% block content %}
<div class="pt-[10rem] w-4/5 h-auto mx-auto my-2">
    <h1 class="mb-6 text-3xl">New conversation</h1>

   <form action="." method="post">
      {% csrf_token %}
      <div class="space-y-4">
        <label class="inline-block mb-2 text-white">Message:</label><br>
         {{ form.content }}
      </div>

      {% if form.errors or form.non_field_errors %}
         <div class="mb-3 p-6 bg-red-100 rounded-xl">
            {% for field in form %}
               {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
         </div>
      {% endif %}

      <button class="mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
   </form>

</div>
{% endblock %}