contact/urls.py
from django.urls import path 
from . import views

app_name = 'contact'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
]

ew/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView
from .forms import LogInForm
from . import views

app_name = 'core'

urlpatterns = [
    path('', views.index, name="index"),
    path('signup/', views.signup, name="signup"),
    path('login/', LoginView.as_view(template_name='ew/login.html', authentication_form=LogInForm), name="login"),
    path('logout/', views.logout_view,  name='logout'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
]

hmk/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from .views import index
from django.conf import settings
from django.conf.urls import handler403, handler404, handler500

urlpatterns = [
    path('atarysworld/', admin.site.urls),
    path('', index, name='index'),
    path('embracewellness/', include('hmk.ew.urls')),
    path('embracewellness/forum/', include('hmk.forum.urls')),
    path('embracewellness/blog/', include('hmk.blog.urls')),
    path('embracewellness/profile/', include('hmk.accounts.urls')),
    path('embracewellness/conversation/', include('hmk.conversation.urls')),
    path('embracewellness/direct_messages/', include('hmk.contact.urls')),
]


urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'hmk.ew.views.page_not_found'
handler403 = 'hmk.ew.views.permission_denied'
handler500 = 'hmk.ew.views.server_error'

contact/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=300, default="Anonymous")
    email = models.EmailField(null=False, blank=False)
    subject = models.CharField(max_length=300, default="No subject")
    message = models.TextField(null=False, blank=False)
    attended_to = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    


contact/forms.py
from django import forms 
from .models import Contact 

INPUT_CLASSES = "text-black border border-gray-400 w-4/5 px-2 placeholder:text-gray-400 py-4 rounded-xl text-left"

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'email', 'subject', 'message']

    name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your Name (or input 'Anonymous')",
        "class": INPUT_CLASSES
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder': "Your Email",
        "class": INPUT_CLASSES
    }))

    subject = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your Subject (or input 'No Subject')",
        "class": INPUT_CLASSES
    }))

    message = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': "Your Message",
        "class": INPUT_CLASSES
    }))

class AttendToForm(forms.ModelForm):
    class Meta:
        model = Contact 
        fields = ['attended_to',]

    attended_to = forms.BooleanField(widget=forms.CheckboxInput(attrs={
        "class": "w-4 h-4 text-mustard bg-mustard border-mustard rounded focus:ring-mustard dark:focus:ring-mustard dark:ring-offset-mustard focus:ring-2 dark:bg-mustard dark:border-mustard"
    }))

contact/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Contact
from .forms import AttendToForm
from django.contrib.auth.decorators import user_passes_test

def is_staff(user):
    return user.is_staff

@user_passes_test(is_staff)
def index(request):
    user_is_staff = request.user.is_staff
    direct_messages = Contact.objects.filter(attended_to=False).all()


    for direct_message in direct_messages:
        direct_message.subject = direct_message.subject[0:50] + "..."

    return render(request, 'contact/contact_index.html', {
        'user_is_staff': user_is_staff,
        'direct_messages': direct_messages,
    })

@user_passes_test(is_staff)
def detail(request, pk):
    message = get_object_or_404(Contact, pk=pk)
    user_is_staff = request.user.is_staff

    if request.method == 'POST':
        form = AttendToForm(request.POST, instance=message)
        if form.is_valid():
            form.save(commit=True)
            return redirect('contact:index')
    else:
        form = AttendToForm(instance=message)

    return render(request, 'contact/detail.html', {
        'user_is_staff': user_is_staff,
        'message': message,
        'form': form
    })


contact/templates/contact/contact_index.html
{% extends 'ew/base.html' %}
{% load static %}
{% block title %}Direct Messages{% endblock %}


{% block content %}
<div class="pt-[2.5rem] w-4/5 mx-auto">
    <div class="flex flex-col justify-center items-center my-10  sm:mx-[15rem]">
        <h2 class="sm:text-5xl text-4xl font-bold z-[2]">Direct Messages</h2>
        <p class=" sm:text-[5rem]  text-[3rem] text-[#343a40]  z-[1] font-extrabold sm:-mt-[4rem]  -mt-[2.5rem]">Messages</p>
    </div>

    <div class="space-y-6 w-full">
        {% for message in direct_messages %}
            <a href="{% url 'contact:detail' message.id %}">
                <div class="flex items-center gap-4  mb-4 text-wrap">
                    <img src="{% static 'images\message.jpg' %}" class=" w-10 md:w-20 h-auto rounded-full"  alt="">
                    <div class="font-medium dark:text-white">
                        <div class="text-lg">{{ message.subject }}</div>
                        <div class="text-sm text-gray-400">New message sent @ {{ message.created_at }}</div>
                    </div>
                </div>
            </a>
        {% endfor %}
   </div>

</div>
{% endblock %}

contact/templates/contact/detail.html
{% extends 'ew/base.html' %}
{% block title %}Direct Message{% endblock %}


{% block content %}
<div class="pt-[5rem] w-4/5 mx-auto">
    <h3 class=" font-extrabold text-white lg:text-2xl text-xl w-full my-4 ">Subject: {{ message.subject }}</h3>
    <p class="text-mustard font-bold flex sm:flex-row  flex-col justify-start  items-start sm:items-center sm:space-x-10 text-sm  my-4">
        <span>
            Sent by: {{ message.name }}
        </span>
        <span>
            Email: {{ message.email }}
        </span>
        <span>
            @ {{ message.created_at }}
        </span>
    </p>
    <p class="text-white text-[1rem] text-lg my-4"   >
        <span class="font-bold">
            Message:
        </span>

        {{ message.message }}
    </p>
    <form action="." method="post">
        {% csrf_token %}
        <div class="flex items-center">
            {{ form.attended_to  }}
            <label for="link-checkbox" class="ms-2 text-sm font-medium text-gray-900 dark:text-gray-300">I have attended to this <a href="#" class="text-mustard  hover:underline">message</a>.</label>
        </div>
        <button class="text-lg font-semibold mt-[1rem] px-3 py-2 bg-black text-black rounded-xl  bg-mustard   hover:bg-white  hover:text-black uppercase">confirm</button>
    </form>
</div>
{% endblock %}